Repository Richixs/TestigosDeJava, pull requests merged in 2024-05, with the labels that each got.

#6 Flujo de trabajo
  README.md
  imagenes/github-flow.png
Labels: documentation

#7 Metodo que convierte de sistama numerico base n a decimal
  CalculadoraSistemasNumericos.java
Labels: enhancement

#8 docs: añade el parrafo buenas practicas
  README.md
Labels: documentation

#9 feature: crea el metodo que convierte un numero a un sistema numerico
  CalculadoraSistemasNumericos.java
Labels: enhancement

#10 feat: suma de dos numeros de sistemas numericos
  CalculadoraSistemasNumericos.java
Labels: enhancement

#11 feat: Crea meotodo de resta de sistemas numericos
  CalculadoraSistemasNumericos.java
Labels: enhancement

#12 feat: crea metodo que multiplica 2 numeros en cualquier sistema numerico
  CalculadoraSistemasNumericos.java
Labels: enhancement

#13 feat: crea metodo que divide 2 numeros en sistema numerico base n
  CalculadoraSistemasNumericos.java
Labels: enhancement

#15 docs/crea tema hooks
  README.md
Labels: documentation

#16 Crea labeler.yml
  .github/workflows/labeler.yml
Labels: configuracion

#18 docs: Agrega la bitacora
  README.md
Labels: documentation

#19 Docs/crear buenas practicas richi
  README.md
Labels: documentation

#20 docs: Agrega la imagen del GitHub Labeler
  README.md
Labels: documentation

#21 docs: evaluacion de richi a nestor
  README.md
Labels: documentation

#22 docs: evaluacion de nestor a sebas
  README.md
Labels: configuracion
